# -*- coding: utf-8 -*-
""" train.py

Automatically generated by Colaboratory.

"""

from tflite_model_maker import image_classifier
from tflite_model_maker.image_classifier import DataLoader

import tensorflow as tf
assert tf.__version__.startswith('2')

import matplotlib.pyplot as plt
import numpy as np


image_path = tf.keras.utils.get_file(
      'flower_photos',
      '/content/imagenes.tar.gz',
      untar=True)

data = DataLoader.from_folder(image_path)
train_data, test_data = data.split(0.9)

model = image_classifier.create(train_data)

loss, accuracy = model.evaluate(test_data)

model.export(export_dir='.')

