# -*- coding: utf-8 -*-
""" train.py

Automatically generated by Colaboratory.

"""

from tflite_model_maker.config import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector
from tflite_model_maker.object_detector import DataLoader

import tensorflow as tf
assert tf.__version__.startswith('2')

import matplotlib.pyplot as plt
import numpy as np


spec = model_spec.get('efficientdet_lite2')

train_data, validation_data, test_data = object_detector.DataLoader.from_csv('/content/drive/MyDrive/Colab Notebooks/labeling/retail/train_labels.csv')



model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)

loss, accuracy = model.evaluate(test_data)

model.evaluate(test_data)


model.export(export_dir='.')

model.evaluate_tflite('/content/model.tflite', test_data)


